# Generated by Django 3.1.4 on 2020-12-24 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar_app', '0002_remove_events_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event', models.CharField(max_length=100)),
                ('important_rank', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User_info',
        ),
        migrations.RemoveField(
            model_name='events',
            name='address',
        ),
        migrations.RemoveField(
            model_name='events',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='events',
            name='important_rank',
        ),
        migrations.RemoveField(
            model_name='events',
            name='note',
        ),
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='events',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
