# Generated by Django 3.1.4 on 2020-12-24 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_auto_20201224_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='events',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
