# Generated by Django 3.1.4 on 2020-12-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_auto_20201224_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('active', 'active'), ('old', 'old')], default='events', max_length=100),
        ),
    ]
