# Generated by Django 3.1.4 on 2020-12-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_events_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('active', 'active'), ('old', 'old')], default='active', max_length=100),
        ),
    ]
