# Generated by Django 3.1.4 on 2020-12-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_auto_20201225_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_type',
        ),
    ]
